#!/bin/python3

import os
import sys

#
# Complete the getTotalX function below.
#
def getTotalX(a, b):
    #variables
    c = a[0]
    small = min(b)
    number = min(b)
    gcd = 0
    lcm = 0
    result = 0
    
    #finding LCM
    if len(a) == 1:
        lcm = a[0]
    else:
        for i in range(len(a)-1):
            d = a[i+1]
            boolean = False
            mult_c, mult_d = c, d
            if c == d:
                c = lcm
            elif c > d:
                while mult_c != mult_d:
                    while mult_c > mult_d:
                        mult_d += d
                        if mult_c == mult_d:
                            lcm = mult_c
                            boolean = True
                    if boolean == True:
                        c = lcm
                        break
                    mult_c += c
            elif c < d:
                while mult_c != mult_d:
                    while mult_c < mult_d:
                        mult_c += c
                        if mult_c == mult_d:
                            lcm = mult_c
                            boolean = True
                    if boolean == True:
                        c = lcm
                        break
                    mult_c += c
    
    
    
    

    #finding GCD
    if len(b) == 1:
        gcd = b[0]
    else:
        for h in range(number):
            mrbool = True
            for z in range(len(b)):
                if b[z] % small != 0:
                    mrbool = False
                    break
            if mrbool == True:
                gcd = small
                break
            else:
                small -= 1

    


    #finding result
    if gcd % lcm != 0:
        return result
    else:
        for y in range(int(gcd/lcm)):
            if gcd % lcm == 0:
                result += 1
            lcm += lcm
        return result

    
            










    







if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    total = getTotalX(a, b)

    f.write(str(total) + '\n')

    f.close()
