#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the birthdayCakeCandles function below.
def birthdayCakeCandles(ar):
    greatest = 0
    results = 0
    for i in range(0, len(ar)):
        if ar[i] > greatest:
            greatest = ar[i]
        
    for j in range(0, len(ar)):
        if ar[j] == greatest:
            results += 1
        
    return results
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
