#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the birthday function below.
def birthday(s, d, m):
    #variables
    big_arr = []
    arr = []
    equation = len(s) - (m - 1)
    b = 0
    result = 0

    #for checking - works well
    for a in range(equation):
        for i in range(m):
            arr.append(s[b])
            b += 1
        big_arr.append(arr)
        arr = []
        b -= (m - 1)
    
        
    
    #check booth - not yet
    for j in range(equation):
        if sum(big_arr[j]) == d:
            result += 1

    return result




    

    



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    s = list(map(int, input().rstrip().split()))

    dm = input().rstrip().split()

    d = int(dm[0])

    m = int(dm[1])

    result = birthday(s, d, m)

    fptr.write(str(result) + '\n')

    fptr.close()
