#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the bonAppetit function below.
def bonAppetit(bill, k, b):
    su = 0
    bill.remove(bill[k])
    su = sum(bill)
    fair = su / 2
    if fair == b:
        return "Bon Appetit"
    else:
        return int(abs(fair - b))


if __name__ == '__main__':
    nk = input().rstrip().split()

    n = int(nk[0])

    k = int(nk[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    print(bonAppetit(bill, k, b))
