#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    num = 0
    res = 0
    cur = '+'
    for i in range(len(s)):
        if s[i] == 'D':
            num -= 1
        else:
            num += 1
        if num < 0 and cur == '+':
            cur = '-'
            res += 1
        if num >= 0:
            cur = '+'
    return res

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
