#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the divisibleSumPairs function below.
def divisibleSumPairs(n, k, ar):
    index1 = 0
    index2 = 1
    res = 0
    while True:
        if (ar[index1] + ar[index2]) % k == 0:
            res += 1
        index2 += 1
        if index2 == len(ar):
            index1 += 1
            index2 = index1 + 1
        if index1 == len(ar) - 1:
            break
    return res
            


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    ar = list(map(int, input().rstrip().split()))

    result = divisibleSumPairs(n, k, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
