#!/bin/python3

import os
import sys
import math
#
# Complete the pageCount function below.
#
def pageCount(n, p):
    if p == 1:
        return 0
    if abs(p - 1) >= abs(n - p):
        if abs(n - p) == 1:
            if n % 2 == 0:
                return 1
            else:
                return 0

        return math.floor(abs(n-p)/2)
    else:
        return math.floor(p / 2)
    
                



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = int(input())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
