#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the kangaroo function below.
def kangaroo(x1, v1, x2, v2):
    #boolean variable
    boolean = False
    #the worst case scenario
    if x2 > x1 and v2 > v1:
        return 'NO'
    elif x1 > x2 and v1 > v2:
        return 'NO'
    elif x1 > x2 and v1 == v2 or x1 < x2 and v1 == v2:
        return 'NO'

    #if it starts out with x1 greater than x2, 
    if x1 > x2:
        while x1 > x2 + 1:
            #if x1 = x2
            if x1 == x2:
                boolean = True
                return 'YES'
                break
            
            #adding x1 and x2.
            x1 += v1
            print(x1)
            x2 += v2
            print(x2)
        if boolean == False:
            return 'NO'
        
        

    #if it starts out with x1 less than x2, 
    if x1 < x2:
        while x1 < x2 + 1:
            #if x1 = x2
            if x1 == x2:
                boolean = True
                return 'YES'
                break
            
            #adding x1 and x2.
            x1 += v1
            x2 += v2
        if boolean == False:
            return 'NO'
       


            
            
            
    


        
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    x1V1X2V2 = input().split()

    x1 = int(x1V1X2V2[0])

    v1 = int(x1V1X2V2[1])

    x2 = int(x1V1X2V2[2])

    v2 = int(x1V1X2V2[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()
