#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumNumber function below.
def check(numbers, lower_case, upper_case, special_characters, password):
    res = 0
    boole1, boole2, boole3, boole4 = True, True, True, True
    for i in range(len(password)):
        if password[i] in numbers:
            boole1 = False
        if password[i] in lower_case:
            boole2 = False
        if password[i] in upper_case:
            boole3 = False
        if password[i] in special_characters:
            boole4 = False
    if boole1 == True:
        res += 1
    if boole2 == True:
        res += 1
    if boole3 == True:
        res += 1
    if boole4 == True:
        res += 1
    return res
def minimumNumber(n, password):
    numbers = "0123456789"
    lower_case = "abcdefghijklmnopqrstuvwxyz"
    upper_case = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    num = 0
    special_characters = "!@#$%^&*()-+"
    if n < 6:
        num = 6 - n 
        if check(numbers, lower_case, upper_case, special_characters, password) > num:
            return check(numbers, lower_case, upper_case, special_characters, password)
        else:
            return num  
    else:
        return check(numbers, lower_case, upper_case, special_characters, password) 





if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    password = input()

    answer = minimumNumber(n, password)

    fptr.write(str(answer) + '\n')

    fptr.close()
